//Set ChatBody Details
export const SET_CHATBOX_DATA_REQUEST = 'SET_CHATBOX_DATA_REQUEST';
export const SET_CHATBOX_DATA_SUCCESS = 'SET_CHATBOX_DATA_SUCCESS';
export const SET_CHATBOX_DATA_FAILURE = 'SET_CHATBOX_DATA_FAILURE';
